import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export async function getStaticPaths() {

    const url = new URL(process.env.URL || 'http://localhost:3000');
    url.pathname = '/api/products';


    const res = await fetch(url.toString());
    
    if (!res.ok) {
        console.error(res);
        return { props: {} };
    }

    const data = await res.json();

    return {
        paths: data.products.edges.map(({ node }) => `/product/${node.handle}`),
        fallback: true,

    }
}

export async function getStaticProps({ params }) {
    const url = new URL(process.env.URL || 'http://localhost:3000');
    url.pathname = '/api/products';

    const res = await fetch(url.toString());

    if (!res.ok) {
        console.error(res);
        return { props: {} };
    }

    const data = await res.json();


    const product = data.products.edges

        .map(({ node }) => {

            if (node.totalInvetory <= 0) {
                return false;
            }
            return {
                id: node.id,
                title: node.title,
                description: node.description,
                imageSrc: node.images.edges[0].node.src,
                imageAlt: node.title,
                price: node.variants.edges[0].node.priceV2.amount,
                slug: node.handle
            }
        })
        .find(({ slug }) => slug === params.slug)


    return {
        props: { product },
    }
}

function Product({slug, imageSrc, imageAlt, title, description, price }) {

    const formattedPrice = new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  });

  return (
    <div className={styles.product}>
      <a href={`/product/${slug}`}>
        <Image src={imageSrc} alt={imageAlt} width={400} height={400} />
      </a>
      <h2>{title}</h2>
      <p>{description}</p>
      <p className={styles.price}>{formattedPrice.format(price)}</p>
    </div>
  );
}



export default function ProductPage({ product }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description"
                    content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>Store</h1>

                <div className={styles.products}>

                    <Product {...product} />

                </div>
            </main>
        </div>
    )
}



