import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export async function getStaticProps() {

  // to be changed, we dont want this to be seen in client side
  const res = await fetch('http://localhost:3000/api/product');

  if (!res.ok) {
    console.error(res);
    return { props: {} };
  }

  const products = await res.json();

  return {
    props: { products },
  }
}

export default function Home({products}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <p>{JSON.stringify(products, null, 2)}</p>
      </div>
    </div>
  )
}



